language: ruby
rvm:
- 2.2
script: bash ./deploy.sh
branches:
  only:
  - develop
env:
  global:
  - GH_REF: github.com/OrlandoDevs/orlandodevs.github.io.git
  - secure: H11McXeHI4JZci7ngenb684HoVk02ODgaDKrq0jBO1QGxH7G9PYoce9ig6bMCgya/ezG/bCLZ7dzrYd5nyVWQhnZhD4XhFJEy383FtA4zq8Ns9/B9xfoGG6SFAPIK7JCaj8QVyv4eWa/o3fRSi5/MFqSnFkd/oyfVb3G77pBMyxzzwyA1ARVr4EqIA5gL/jNGWnljfjZ9kV5XWD5b5OdYkEHQ13enoqjbAi6QtwAEmDfebCMjO/e+EORHW2oZA+DM7Tu2MW5LeKcQ62OZ6g7CYGB/iU4axWQ0lIIg0yLGkeax3L3wVrv5XksRqvyqnYkHwGHPaaEF+FfliLWbXoAZ9+U/rlbgMDke85VGCORWzHgrkTTDJMOaLTbGvZoO0k+sYh5+hrcg8lhVGy25P0rRoyvmTmidbPQVh1UgpW1AwSr2W2hAXE6IvleJKUKH7IR0zby3SyBWoJBHdJaJ0Ujj3St6wti5VEgVLgkJfqctF1pgE2maCusC0/62tv3h1aw+7sOJARZ9lJ9HGvyk4DmnQz9X+Nn2pS/RmmOl5N2KL9o9pgC8YBGU/UlMVuPk9GzsTdaNL8t3at4Uedt3NzS/uMsiFXZwQ01A+hsD0SVvFDJS8fmV56LyXBH0VU2CX6UZqdRhel46DCYAKpLSmXisapX17RhmpxK/I6/v4ofgOc=
  - secure: HJLrbI+/h9ie1HOG5YGN7TR+Sh/QZ3GSaqdl7bybMXPJS/TDLrOeQ8dYalM+ksHTFaVM2yaJCfXtYCl5vvwpgNS8iJFa5Lwblhqq2ns/cSGpfDoO21R6KkWNTSyod1WHB9MpIGd+Z0Hrs9YzxnamrEMMV1S8I2Sqwr30YhaMSkUPxuGkAgQdq0ZG76BAphw7w5j+o2It0739tCGIwkT/vtmWs/epKnNb0DrT/ImjxSgMbqo9X+5kmniJ78OVkP9Q/P4Oof0dompBSB1X5JDVvIKFH+MMjYWS+AytToE0vrmrfkjhkeUrFaQymf29t4c3OqBI2wWGXV4pq22i+VNWKFtC1cAC4auyI5PGMjuYEDl+OScFVRjlYbEvyXWEOB5j1aQ8wwfhSDUtQM4aiIAmgGC+YFTln+6d8azI1F49GRvBGMTirHu6WZsCCSOMRivCOe2i8XZTOuGxUm/Vt1MmaOj2ceC7vHh4JtwxBrpVF1fOxKEYDvvIQvFUaQP1LTWI778f+WWxoF3yi+mMLy6cQOAhD0EelVZV62hMGvKPlTvXEaH7NVczcsiLdoALPGzQINvHvnd8rxhZXaK0SJSDZBPwyZolFCOdVYzicVTAAV35sjGxqS3dswdtoOAuG6oBsLx50EMOC1F9rgm7s1oiIBl6WiGD4GzCg6Oxes6O+8k=
